### ISSUE TITLE
The `Rules` property should be made public

### ISSUE THREAD

**Issue by itaibh** [TylerBrinks/ExCSS#100]
I want to be able to track each `@import` rule, while keeping the order of the other rules.
To make things more clear - think of `@import` as a C++ macro command (which in sort it actually is); what I want is to be able to get the entire CSS text. For that I need the `Rules` property (which is currently `internal`) to be made `public`. Then I could traverse all the rules, write each "simple" rule to a `StringBuilder` (for instance), and for each `@import` rule I encounter I will call the same method recursively.

**Comment by HockeyJustin** [comment]
Just to add to this - yest there are a lot of classes that are currently internal that should be public. 

This pull request [Fixed: StyleRule didn't implement interface IStyleRule](https://github.com/TylerBrinks/ExCSS/pull/97) seems to have everything needed. Please can you merge and publish to NuGet. The current NuGet package is unusable for me.

**Comment by HockeyJustin** [comment]
@emiliano84 - Done. https://www.nuget.org/packages/ExCSS-Core/. Tried to contact @TylerBrinks via nuget and github, but no response. I would have preferred to be a contributer to this project than fork it.

**Comment by emiliano84** [comment]
@HockeyJustin thank you so much for your work, I totally agree about the fact to be a contributor, but due the circumstances a fork mentioning the great job done by the author is the best way to go, at least till will have some news back from @TylerBrinks  

p.s.
if you like you could rename the GitHub repo to ExCSS-Core to reflect the nuget name

**Comment by emiliano84** [comment]
@HockeyJustin sorry to bother you again, could you update your package and make stylerules available in stylesheet.cs?

public IEnumerable<IRule> StyleRules => Rules.Where(r => r is StyleRule);

thanks

p.s.
would be nice if you could enable issues tab in your repo, if you're willing to maintain this package of course :)

**Comment by HockeyJustin** [comment]
@emiliano84 - Issues tab now set up and project updated/ published to NuGet. Good suggestion btw.
