### ISSUE TITLE
StylesheetParser.Parse throws ArgumentOutOfRangeException

### ISSUE THREAD

**Issue by Metalnem** [TylerBrinks/ExCSS#101]
**StylesheetParser.Parse** throws an **ArgumentOutOfRangeException** with the following message:

> An unhandled exception of type 'System.ArgumentOutOfRangeException'
> occurred in System.Private.CoreLib.dll: 'A valid UTF32 value is between
> 0x000000 and 0x10ffff, inclusive, and should not include surrogate
> codepoint values (0x00d800 ~ 0x00dfff).'

You can run the following code to reproduce it (the **path** variable should contain the path to the file extracted from the [attached archive]):

```csharp
using (var file = File.OpenRead(path))
{
  var parser = new StylesheetParser();
  parser.Parse(file);
}
```

Found via [SharpFuzz].

[attached archive]: https://github.com/TylerBrinks/ExCSS/files/2707023/ArgumentOutOfRangeException.zip
[SharpFuzz]: https://github.com/Metalnem/sharpfuzz

**Comment by TylerBrinks** [comment]
Please verify in version 4.0 if the issue still exists.
