### ISSUE TITLE
Is the project still active?

### ISSUE THREAD

**Issue by mrbean-bremen** [TylerBrinks/ExCSS#102]
We are using ExCSS in [SVG.NET](https://github.com/vvvv/SVG) and have been making a few fixes there some time ago.
We are [now considering](https://github.com/vvvv/SVG/issues/563#issuecomment-526838582) to make a PR with these fixes in this project (provided a new nuget will be released), or create and use a fork of the project, if this is not possible because the project is no longer maintained.

Is this still maintained, or is there an active fork that can be used?

**Comment by mrbean-bremen** [comment]
Ok, there seems to be a [more recent fork](https://github.com/HockeyJustin/ExCSS_Core/) with .NETStandard support. Lokks like this repo is indeed unmaintained.

**Comment by TylerBrinks** [comment]
It's alive, yes.  It was just taking a nap!
