### ISSUE TITLE
justify-content and align-items always empty

### ISSUE THREAD

**Issue by arakis** [TylerBrinks/ExCSS#108]
`justify-content` and `align-items` is always empty. Here's a small Unit test:

```c#

// will work
[Fact]
public void ParseFontSize()
{
    var parser = new ExCSS.StylesheetParser();
    var sheet = parser.Parse("a {font-size:10px; }");
    var style = ((ExCSS.StyleRule)sheet!.StyleRules!.First()).Style;
    Assert.Equal("10px", style.FontSize);
}

// will fail
[Fact]
public void ParseJustifyContent()
{
    var parser = new ExCSS.StylesheetParser();
    var sheet = parser.Parse("a {font-size:10px; display: flex; justify-content: center; }");
    var style = ((ExCSS.StyleRule)sheet!.StyleRules!.First()).Style;
    Assert.Equal("10px", style.FontSize);
    Assert.Equal("center", style.JustifyContent); // will fail
}
```

Output:
```
  Message: 
    Assert.Equal() Failure
              ↓ (pos 0)
    Expected: center
    Actual:   
              ↑ (pos 0)
```

`display: flex` with `justify-content` is a valid combination:
https://developer.mozilla.org/de/docs/Web/CSS/CSS_Flexible_Box_Layout/Aligning_Items_in_a_Flex_Container

**Comment by arakis** [comment]
It works if i set `includeUnknownDeclarations: true`. The question remining: Why are these properties "unknown"?

**Comment by TylerBrinks** [comment]
Try reversing the order and put the display: flex as the last rule.  It may be that the parser needs to be updated with the flex rule.  Typically I break a style down into individual rules to troubleshoot.  If it's reproducible as a single rule, it's easier to track down.

**Comment by TylerBrinks** [comment]
The property matrix is missing a JustifyContent rule.  I've added the missing property map and will publish it to NuGet shortly.
