### ISSUE TITLE
Make method ParseDeclaration public

### ISSUE THREAD

**Issue by arakis** [TylerBrinks/ExCSS#109]
Please make the method `ParseDeclaration` public. You need such method if you're parsing inline style from an DOM style attribute.

https://github.com/TylerBrinks/ExCSS/blob/b8989f6c0fa6edab87530f7e60cfdb0df0d3ef39/src/ExCSS/Parser/StylesheetParser.cs#L154-L157

Or is there an alternativ method? My current workarround is:
```c#
parser.Parse("dummy {" + styleBlcok + "}");
```

**Comment by TylerBrinks** [comment]
Hi  @arakis  .I'm not sure I understand the use case here.  What are you trying to accomplish?  Parsing a declaration depends on the parent rule for context.  In other words, it's not just parsing text; it's building an object model.  Declarations require a surrounding rule to provide a context.

**Comment by arakis** [comment]
Like in #110, they have the same approach: Working with **Inline**-Styles, like `<div style="color: red">`.

`ParseDeclaration` is requiered to **PARSE** inline-style, the issue in #110 is required to **GENERATE** inline-style.

Even in your unit tests you make a heavy approach of these methods - for good reasons - to avoid adding always a useless dummy selector like
```
parser.Parse("dummy {" + inlineStyle + "}");
```

For your information, i'm working on a HTML-Layout engine: https://github.com/AximoGames/AxGui

**Comment by TylerBrinks** [comment]
This isn't a use case the library is intended to support.  This would introduce a declaration without the context of a rule.  In your example, it's implied that the underlying style rule is `div{ color: red}` for a div tag specifically.  

In general, the library is intended to parse a stylesheet independent of markup.  When styles are mixed inline, you have to remember that browsers are making assumptions on your behalf.  Inline is the same as if you gave an element a unique name and then put a named style into an external stylesheet.  In either case, the declaration never exists outside a rule.  I'm not sure I see the use case yet.

**Comment by arakis** [comment]
I understand what you mean. But i do not want any extra logic done by the libraray, i just want parse and generate the StyleDeclration of inline-style. I could write my own parser, but i found ExCss, so i'm using that one for now.

It's ok if you do not agree, as long i'm able to use my dummy-selector workaround for parsing and generating. It was just an idea for an improvement just to make the two methods/constructor public to make the library more powerful.

**Comment by TylerBrinks** [comment]
I don't disagree.  It's helpful to try and understand the use case before changing the API's signature.

If you want to create a PR with full test coverage I'm happy to consider it.
