### ISSUE TITLE
Make Constructor of StyleDeclaration public

### ISSUE THREAD

**Issue by arakis** [TylerBrinks/ExCSS#110]
Is there any reason why the constructor of StyleDeclaration is private?

The currente workarround is:
```c#
var parser = new ExCSS.StylesheetParser(includeUnknownDeclarations: true, tolerateInvalidConstraints: true, tolerateInvalidValues: true);
var rule = new ExCSS.StyleRule(parser);
var decl = rule.Style;
```

It's usefull if you want generate css output:
```c#
decl.BorderBottom = "5px";
var sb = new StringBuilder();
var writer = new StringWriter(sb);
decl.ToCss(writer, ExCSS.CompressedStyleFormatter.Instance);
var str = sb.ToString();
```

**Comment by TylerBrinks** [comment]
HI @arakis, 
In short, a declaration can't exist outside the context of a style rule.  Without a selector, a declaration has no concept of what the style applies to.  Declarations are constrained by their declaring rule type hence their sealed, private/internal constructors.  Changing the behavior would require injecting a parser and parent rule which would defeat the purpose of an encapsulated declaration.

An alternative if you want quick access to CSS is simply calling ToCss on the top level sheet:

```
var sheet = new StylesheetParser().Parse("h1{ color: #abc; }");
var css = sheet.ToCss();
```
