### ISSUE TITLE
StyleDeclaration.ToCss writes more properties than given

### ISSUE THREAD

**Issue by arakis** [TylerBrinks/ExCSS#111]
Take the following code snipped:

```c#
var parser = new ExCSS.StylesheetParser(includeUnknownDeclarations: true, tolerateInvalidConstraints: true, tolerateInvalidValues: true);
var rule = new ExCSS.StyleRule(parser);
var decl = rule.Style;
decl.BorderBottom = "5px";
var sb = new StringBuilder();
var writer = new StringWriter(sb);
decl.ToCss(writer, ExCSS.CompressedStyleFormatter.Instance);
var str = sb.ToString();
Assert.Equals("border-bottom-width: 5px", str)
```

. | Value
--- | ---
Expected | `border-bottom-width: 5px`
Actual | `border-bottom-width: 5px; border-bottom-style: initial; border-bottom-color: initial`

I know they are one "group", but it would mess up the output, if you use them heavily to re-produce css output.

Why are this extra values generated and is there a way to disable this?

**Comment by TylerBrinks** [comment]
Hi @arakis, the way the parser engine works is by using a pair of "Longhand" and "Shorthand" dictionaries when mapping properties.  If you open up a browser's developer tools and evaluate an element, you'll typically find a visualizer for Computed Properties that explain how any given element's styles are calculated.  For example, when you specify a border-bottom in CSS property, you're using a shorthand syntax.  The following are all valid for border-bottom:

```
border-bottom: 5px solid red;
border-bottom: 4px dotted blue;
border-bottom: double;
```

The first example is short for

```
border-bottom-width: 5px;
border-bottom-style: solid;
border-bottom-color: red;
```

You're setting the short hand property and getting longhand output.  The correct approach if you want input to match output is to set the style as follows

What you want is:
`decl.BorderBottom = "5px";`

**Comment by arakis** [comment]
Thanks for the clarification, it was a typo by me. You're totally right, of course.
