### ISSUE TITLE
Make selector public

### ISSUE THREAD

**Issue by cbersch** [TylerBrinks/ExCSS#112]
Hi,

we're currently using ExCSS 2.0.6 and would like to upgrade so version 4. I'm very pleased to see the development going on!

Our use case is to parse CSS style sheets and apply those to our business model. 
That requires also evaluating the selectors, which aren't available any more for public use, but have been made internal (`ComplexSelector`) or even privat (`CombinatorSelector`).

**Comment by TylerBrinks** [comment]
Can you provide a short example of what you're trying to accomplish?  The API should let you get at most properties and values; an example would help clarify.

**Comment by cbersch** [comment]
Here is an example which should show, what we do:

~~~
using ExCSS;
using FluentAssertions;
using NUnit.Framework;
using System.Collections.Generic;
using System.Linq;

namespace ExCSSExample
{
	[TestFixture]
	public sealed class ExampleTest
	{
		[Test]
		public void Test()
		{
			var parser = new StylesheetParser();
			var stylesheet = parser.Parse("foo > bar {color: red; }");
			var rule = stylesheet.StyleRules.First() as StyleRule;

			var child = new Model("bar");
			var model = new Model("foo", child);

			if (Match(child, rule.Selector))
				ApplyCssToModel(child, rule.Style);

			child.Properties.Should().Equal(new Dictionary<string, string>()
			{
				{"color", "rgb(255, 0, 0)" }
			});
		}

		private bool Match(Model model, ISelector selector)
		{
			// TODO: this must evaluate the actual selector structure
			return true;
		}

		private void ApplyCssToModel(Model model, StyleDeclaration style)
		{
			foreach (IProperty p in style)
				model.Properties[p.Name] = p.Value;
		}
	}

	public sealed class Model
	{
		public string Name { get; }
		public IDictionary<string, string> Properties { get; } = new Dictionary<string, string>();
		public IEnumerable<Model> Children { get; }
		public Model Parent { get; private set; }

		public Model(string name, params Model[] children)
		{
			Name = name;
			Children = children;
			foreach (var child in children)
				child.Parent = this;
		}
	}
}
~~~

For the actual implementation of the `Match`-method, we need access to the selectors, so that we can evaluate if  a `Model` instance matches a given style rule.

The required changes would be those from two commits of https://github.com/TylerBrinks/ExCSS/pull/97

**Comment by TylerBrinks** [comment]
I think you have access to the selector using:

```(stylesheet.StyleRules.First() as StyleRule).SelectorText```

**Comment by TylerBrinks** [comment]
See version 4.1 

```stylesheet.StyleRules.First().SelectorText```

**Comment by cbersch** [comment]
The `SelectorText` doesn't help me much, because I need its parsed structure for evaluating it. That's why I gave that little more complex example with `foo > bar` as selector.

Here, I need to know, that the selector is a `ComplexSelector` and then match it against my model.

**Comment by TylerBrinks** [comment]
I'm happy to look at a pull request.  I'm not sure I can infer from your example what change to make specifically.

**Comment by cbersch** [comment]
This was fixed with issue https://github.com/TylerBrinks/ExCSS/issues/142
