### ISSUE TITLE
Support for css variables

### ISSUE THREAD

**Issue by CrescentFresh** [TylerBrinks/ExCSS#118]
The following is an example of parsing (and using) [custom css properties](https://developer.mozilla.org/en-US/docs/Web/CSS/Using_CSS_custom_properties) (aka variables):

```
var parser = new StylesheetParser();
var stylesheet = parser.Parse(@"
    :root {
        --my-color: rgb(147, 30, 45);
    }
    a {
        color: var(--my-color);
    }
");
var c = stylesheet.StyleRules.First(sr => sr.SelectorText == "a").Style.Color;
```

I would expect the value to be `"rgb(147, 30, 45)"` or at the very least `"var(--my-color)"`. Today it is the empty string.

Likewise I would expect I could get the value of any css property including custom ones such as the above like this:

```
stylesheet.StyleRules.First(sr => sr.SelectorText == ":root").Style.GetPropertyValue("--my-color");
```

Today that also yields the empty string instead of the expected `"rgb(147, 30, 45)"`.

**Comment by TylerBrinks** [comment]
I'm happy to take pull requests

**Comment by CrescentFresh** [comment]
I'm not familiar with the process of making a feature request in this repo. What does it mean when the ticket is closed with a comment "happy to take pull requests"? 

I did not intend for the presence of the issue to mean "something is broken", it's is more just a reference placeholder.

If I want to write this feature and submit a pull request are you saying I should create a new issue? Was there something wrong with this one?

**Comment by TylerBrinks** [comment]
Issues represent a deficiency in the codebase that require remediation.  Unless there's a code problem there's no issue, hence the closed ticket.  Some large scale projects have a staff that takes community feedback which in turn become features.  In the case of smaller projects, such as this one, they're maintained by people with day jobs.  You're welcome to  fork the code into your own branch, make the change you want, and submit a pull request for integration into the codebase.  However I don't personally have bandwidth to take feature requests and do extra curricular work.  You're welcome and encouraged to be an open source contributor!

**Comment by CrescentFresh** [comment]
Ah ok. When I have a pull request ready in other projects I've contributed to there is usually a reference to the ticket that outlines the problem, for example `"Implements #999"`, that way there is a issue people can reference to understand what the PR is about.

I can duplicate the description in this issue in the PR when the time comes.
