### ISSUE TITLE
parse error!!

### ISSUE THREAD

**Issue by colindcli** [TylerBrinks/ExCSS#121]
parse error!!
[media_1.zip](https://github.com/TylerBrinks/ExCSS/files/7038870/media_1.zip)

**Comment by TylerBrinks** [comment]
I'm happy to look at a code sample, but I'm not inclined to download a random zip file.  Please feel free to elaborate and point out a specific use case that's failing the the form of a standard issue with a description of expected vs actual behavior.

**Comment by colindcli** [comment]
The reason is found, it is because of utf-8 bom, there are two bom caused.
