### ISSUE TITLE
How can I get and set nested @page attributes.

### ISSUE THREAD

**Issue by minkichoe** [TylerBrinks/ExCSS#122]
```
@page {
    size: A4;
    margin: 30mm 15mm;

    @bottom-right {
        content: counter(page);
    }
}
```

stylesheet.ToCss();
```
> <style>
@page * { size: A4 margin: 30mm 15mm }
</style> { }
```

Hi, How can I get @bottom-right?

**Comment by TylerBrinks** [comment]
Thanks for the question.  The current @page rule does not account for "at" attributes as child rules which is a bug.  I'll work on a fix and deploy a new version to NuGet.

**Comment by TylerBrinks** [comment]
The 4.1.1 update has support for @page attributes with nested margins with @ prefix values.

**Comment by minkichoe** [comment]
Thanks for your answer.
