### ISSUE TITLE
Invalid parsing at windows OS file path structure.

### ISSUE THREAD

**Issue by minkichoe** [TylerBrinks/ExCSS#123]
Hi, how can I get correct url?

Sample code:
```
FileInfo f = new FileInfo(@"C:\projectdir\bin\x64\Debug\net48\image.png");
string rawStyleRule = $".a {{ background-image: url('{f.FullName}'); }}";

var parser = new StylesheetParser();
var stylesheet = parser.Parse(rawStyleRule);
var rule = stylesheet.StyleRules.First() as StyleRule;

Console.WriteLine(f.FullName);
Console.WriteLine(rule.Style.BackgroundImage);
```

Results:
```
C:\projectdir\bin\x64\Debug\net48\image.png
url("C:projectdir\b inx64෫ugnet48image.png")
```

**Comment by TylerBrinks** [comment]
Your css isn't valid.  You have 2 sets of curly braces after the class identifier where there should be a single set.  Second, your path isn't valid per CSS specs.  The URL function accepts an absolute URL, relative URL, or data URI.  Your path, having backslash characters, will be truncated by the parser.  However if you remove the extra braces you will see a URL that's parsed without the slash characters
