### ISSUE TITLE
Detect and report parse errors in CSS

### ISSUE THREAD

**Issue by gerhardol** [TylerBrinks/ExCSS#132]
Version: 4.1.3

With v2 of this project, it was possible to get parse errors with `stylesheet.Errors.Count`
In v3 and later, this is no longer available. There is a handler for lexer error, but that is not public.
Parsing errors are just silently ignored.
~Parse errors seem to be reported with "empty" StyleRules, but I also get that occasionally as an additional last rule for seemingly correct documents. (That is likely a separate issue.)~
See also #94 

Is there another way to detect parse errors?

**Comment by TylerBrinks** [comment]
I'm happy to take pull requests.  However I'm closing this post since it's not an error that can be acted upon.
