### ISSUE TITLE
ListSelector should be a public class

### ISSUE THREAD

**Issue by thabing** [TylerBrinks/ExCSS#142]
So far I am very impressed with your ExCSS library.  Thanks for the great work.  However, there is one issue that is holding up my work a bit.

If I am interpreting the CSS spec correctly (i.e. see https://stackoverflow.com/questions/37743715/specificity-rules-for-comma-delineated-lists), I think in order to apply styles to the matching elements from a ListSelector, I need access to each child selector's Specificity separately.  Currently this doesn't seem possible because the ListSelector class is internal; there is no way to enumerate each of the component selectors individually.

Currently, the Specificity of the ListSelector seems to be the sum of the Specificity of its children.  However, given my reading of the spec, the overall Specificity of the List isn't really meaningful.  You need to evaluate the Specificity of the separate selectors in the list.

I'm happy to hear alternate interpretations of this.

**Comment by TylerBrinks** [comment]
I understand what you're suggesting.  I don't mind either changing the access of a class (where it makes sense) or adding a relevant method that all implementations can use.  I can take a look but it would be immensely helpful if you could submit a pull request with a unit test or something we can go off of, even if it's not yet functional.  We can implement it once we have a spec to use as the roadmap.  Sound fair?

**Comment by gdeswardt** [comment]
This has now been released along side more specific selectors in version 4.2.0
