### ISSUE TITLE
Everything's that's useful is internal

### ISSUE THREAD

**Issue by borup3** [TylerBrinks/ExCSS#165]
When I parse a background-image I want to grab the parsed url component. When I parse a color I want to grab the parsed rgb/rgba component. All the work is already done inside ExCSS with BackgroundImageProperty and ColorProperty. Why are these values only exposed in the public API as re-stringified versions we have to parse _again_? Am I missing something?

**Comment by TylerBrinks** [comment]
I'm happy to take pull requests that add features that the library doesn't provide.  There are different ways to build a lexer and the underlying object model it populates.  In the case of CSS, the valid text variants are loose at best, and the project was started long before there were C# concepts like discriminated unions (still not available in C#; workarounds exist).  The unit tests cover most of the valid `background-image` values if you want to look at a few variants.  For example, the following are all valid `background-image` values:

- background-image: none
- background-image: linear-gradient(135deg, red, blue)
- background-image: url("img/sprites.svg?v=1bc768be1b3c"),none
- background-image:: url("data:image/png;base64,.......)

In other words, there is no guarantee that you can simply grab the parsed URL component when there may not be one.  I don't have any objections to expanding the public API so long as it doesn't affect the parser.
