### ISSUE TITLE
Copyright placeholder in your license.txt file

### ISSUE THREAD

**Issue by sla80** [TylerBrinks/ExCSS#173]
Hello! Why don't you fill a valid copyright in your license?
https://github.com/TylerBrinks/ExCSS/blob/master/license.txt
There is a placeholder:
`Copyright (c) [year] [fullname]`
Which normally should be filled to make the MIT License valid. Should be something like this:
`Copyright (c) 2024 Tyler Brinks`

**Comment by TylerBrinks** [comment]
Updated license
