### ISSUE TITLE
How to use selectors?

### ISSUE THREAD

**Issue by borup3** [TylerBrinks/ExCSS#177]
How can I use ExCSS to find a style with a selector?

If I have this CSS
```
button > text .link {
   ...
}
```

How can I use ExCSS to find that style after parsing the stylesheet?

**Comment by TylerBrinks** [comment]
Try the example in the repository readme.  It shows the standard pattern for accessing style rules.

**Comment by borup3** [comment]
Yes, but inverted. Can I turn the string `button > text .link` into an ExCSS StyleRule that I can compare with other style rules to see if they match in a way that follows CSS? For example, the above would get the `.link` rule, the `button > text` rule, the `text .link` rule etc. Or is that not a problem that ExCSS solves?

**Comment by TylerBrinks** [comment]
Yes, you can use the object model if you parse the stylesheet.  Look at the children property which will have a style rule with 2 additional children, in the case of your example.   You can use the model properties to compare however you like.
