### ISSUE TITLE
"Opacity" is parsed incorrectly in version 4.2.6

### ISSUE THREAD

**Issue by cwall-dev** [TylerBrinks/ExCSS#180]
In version 4.2.6, "opacity: 1" is parsed as "opacity: 0.01%". This is likely due to the fix for issue #176 
![image](https://github.com/user-attachments/assets/f54bcac3-5cb9-4fcd-8acd-5063c2475c0b)

**Comment by TylerBrinks** [comment]
Fixed in the 4.2.7 release
