### ISSUE TITLE
@Media enclosed css

### ISSUE THREAD

**Issue by jamesthecat7** [TylerBrinks/ExCSS#41]
Parser is unable to deal with css enclosed within @media element. Example here: http://www.google.com/about/default.css 

Google use '@media screen,projection{' to encapsulate all remaining css. This causes EXCSS to throw NotSupportedExceptions from the methods 'AddSeparator' and 'AddTerm' in TermList.cs

Is it possible to make it handle this by telling it to close curley braces before the next element?

**Comment by TylerBrinks** [comment]
The engine may need to be updated to understand the slight difference in rule set inside a media query.  It's something I'd like to add for sure.

**Comment by TylerBrinks** [comment]
I'm not able to reproduce this - the current unit tests are passing media element parsing
