### ISSUE TITLE
Calculate final styles by taking cascades into account

### ISSUE THREAD

**Issue by Piedone** [TylerBrinks/ExCSS#5]
First of all a big thank you for creating this awesome read-write CSS parser! Actually I think it's the only one (besides its parent project) for .NET.

Would it be possible for the parser to calculate the final, actual styles after parsing the stylesheet? Like merge declarations by selectors? E.g. if there's a color: #fff declaration for body on ln 3, and a color: #000 on ln 50 the parser would calculate that the actual colour is #000.

**Comment by dajbych** [comment]
I have written a style computation processor which does exactly this – [ApplyCSS](https://github.com/dajbych/applyCSS).

**Comment by Piedone** [comment]
@dajbych Nice!
