### ISSUE TITLE
IE Star hack not handled properly

### ISSUE THREAD

**Issue by guillaume-fr** [TylerBrinks/ExCSS#54]
ExCSS doesn't handle properly the [CSS Star hack](http://en.wikipedia.org/wiki/CSS_filter#Star_hack)

    var x = new ExCSS.Parser().Parse("body { *display: inline; }");
    // x.Errors.Count == 1 but I expected 0
    // x.Rules[0].ToString() == "body{display:inline;}" => we have lost the *

**Comment by TylerBrinks** [comment]
Do you mind submitting a pull request for that?

**Comment by guillaume-fr** [comment]
Hi Tyler,
I tried and hope I didn't break anything, all tests are green :)
Your tests might be improved by asserting more on returned rules than ToString output. That would give a better confidence when somebody with little knowledge of your implementation (like me) send a pull request.

**Comment by TylerBrinks** [comment]
Go ahead and send a pull request and I'll merge it into the project after testing it.
