### ISSUE TITLE
Keep comments?

### ISSUE THREAD

**Issue by Petoj87** [TylerBrinks/ExCSS#58]
Is there any way to keep comments (in some cases those contain licenses that should not be removed?)

**Comment by TylerBrinks** [comment]
The goal of this project isn't to reproduce CSS to be re-rendered for public consumption.  The goal is to build an object model around the hierarchy.  Hence comments aren't accounted for.

**Comment by rh78** [comment]
I understand that point. But then the StylesheetParser "preserveComments" flag should be gone, or at least - in source code - the CompressedStyleFormatter should not contain a comment rendering section. It is misleading.

Btw., the CompressedStyleFormatter and the ToCss method suggest, that the library is indeed thought for re-rendering CSS. Or was that not in the library in 2015?

Reason for the input is, that we use ExCSS to validate CSS input, and we would really like to then output the CSS again for (safe) consumption.

**Comment by TylerBrinks** [comment]
The code today is a far cry from 2015.  The whole library was rewritten since that post.

**Comment by AnderssonPeter** [comment]
You don't have to fix any thing on my account I don't use this any more! (But when I did it was great)
