### ISSUE TITLE
Parsing inline styles

### ISSUE THREAD

**Issue by dajbych** [TylerBrinks/ExCSS#59]
If an inline style string `color: red; font-size: 2em` could be parsed to *IList&lt;Property&gt;* it would be very helpful.

**Comment by icnocop** [comment]
Was this issue closed because there aren't any plans to implement it?

Thank you.

**Comment by TylerBrinks** [comment]
Nope - the new version, version 3, has been pushed to GitHub.  We'll be closing issues related to v2 as the new version supersedes the old one.
________________________________
