### ISSUE TITLE
Extracting Urls with v2

### ISSUE THREAD

**Issue by netclectic** [TylerBrinks/ExCSS#63]
Hi,

I am currently using v1.1.0 to extract urls from css using this code:

```
	var parser = new StylesheetParser();
	var styleSheet = parser.Parse(cssText);
	var cssUrlTerms = styleSheet.RuleSets
		.SelectMany(r => r.Declarations)
		.SelectMany(d => d.Expression.Terms)
		.Where(t => t.Type == TermType.Url)
		.Union(
			styleSheet.Directives.SelectMany(d => d.RuleSets)
			.SelectMany(r => r.Declarations)
			.SelectMany(d => d.Expression.Terms)
			.Where(t => t.Type == TermType.Url)
		)
		.Distinct()
		.ToList();
```

I don't see a way to do something similar with v2, am I missing something?

**Comment by TylerBrinks** [comment]
Here's how it would work to look up terms with a URI type

```
var terms = css.StyleRules.SelectMany(sr => sr.Declarations)
    .Select(dclr => dclr.Term)
    .OfType<PrimitiveTerm>()
    .Where(term => term.PrimitiveType == UnitType.Uri)
     .Select(term => term.Value);
```

**Comment by Athl33t** [comment]
With the new syntax how would we get image Urls which are not primitive? 

For example this css does not get picked up when we use .OfType<PrimitiveTerm>()
background: url(http://imgpg.jobing.com/company/images/138/t/bg_footer.png) no-repeat scroll 0px 0px;
I only want to capture the imageurl, not the full css text
