### ISSUE TITLE
Incompatible with .NET 4.5.2

### ISSUE THREAD

**Issue by dajbych** [TylerBrinks/ExCSS#65]
When the ExCSS library version 2.0.6 is referenced by .NET 4.5.2 assembly, it cannot be compiled. _The type 'System.Object' is defined in an assembly that is not referenced. You must add a reference to assembly 'System.Runtime, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'._
Update: It happens only in VS 2013. VS 2015 RC is not affected.

**Comment by TylerBrinks** [comment]
Is there a simple way to reproduce this issue?  I'd like to close it if I can find a fix.
