### ISSUE TITLE
Nuget Package Incompatible with .NET 4

### ISSUE THREAD

**Issue by rwil02** [TylerBrinks/ExCSS#68]
Project refuses to build when set to 4.0, even though it is referencing packages\ExCSS.2.0.6\lib\net40

"Indirect Reference" issues include System.Runtime, System.Collections, etc.
Changing to 4.5 resolves this

**Comment by netclectic** [comment]
Same issue here.
I am unable to change to 4.5 but rolling back to ExCSS 2.0.5 resolves the issue.

**Comment by TylerBrinks** [comment]
I'll try to test out the package with various target frameworks before the next patch.

**Comment by dittodhole** [comment]
The problem: Your Net40 assembly is actually a .NETPortable 4.5 ...

**Comment by TylerBrinks** [comment]
Current package version 4.0 supports .net core 3.1 and .net 4.8
