### ISSUE TITLE
Bad parse result when filtering with attribute and pseudo class

### ISSUE THREAD

**Issue by attilah** [TylerBrinks/ExCSS#69]
For this css:

input[type="reset"]::-moz-focus-inner
{
    margin: 0;
}

I get a selector list of 3 simple selectors:
input
[type="reset"]
::moz-focus-inner

I think it should be a complex or other type of selector but it should be 1 selector in the parsed result.

This behavior has a side effect for this css:

input[type="reset"]::-moz-focus-inner,a,b,c
{
    margin: 0;
}

All is the same like before, but:
- The selector list has no sepeator
- a,b,c also parsed as pseudo classes

**Comment by TylerBrinks** [comment]
Can you point to a css 3 spec that supports this or how it's incorrect?
