### ISSUE TITLE
Exception on parsing Unicode string

### ISSUE THREAD

**Issue by SpeedSX** [TylerBrinks/ExCSS#70]
I've got an exception parsing a stylesheet with the following rule:

p.berschrift1, div.berschrift1
{mso-style-name:"\00DCberschrift 1";
mso-style-link:"\00DCberschrift 1 Zchn";
font-size:12.0pt;
font-family:"Times New Roman", "serif";}

Parser fails to convert a string "\00DCberschrift 1" because it tries to interpret 6 characters in ConsumeEscape method. I've changed this to 4 and now it works fine.
What do you think, is this fix correct?

**Comment by bfreese** [comment]
I don't think that's correct. The spec says 1-6 characters with an optional white space character.
[See Here](http://www.w3.org/TR/css-syntax-3/#escaping0)

**Comment by TylerBrinks** [comment]
I'd agree.  The spec spec does speak to anything 1 to 6 in length.

**Comment by bfreese** [comment]
ConsumeEscape should probably report the error and absorb whatever characters it could parse as a valid UTF32 value and move on.

**Comment by TylerBrinks** [comment]
I think that makes sense.  I'll have to see specifically what exception is thrown and handle it accordingly
