### ISSUE TITLE
IndexOutOfRange exception in StringExtensions.TrimFirstLine

### ISSUE THREAD

**Issue by MaceWindu** [TylerBrinks/ExCSS#73]
```
System.IndexOutOfRangeException occurred
  StackTrace:
       at System.Text.StringBuilder.get_Chars(Int32 index)
       at ExCSS.Model.Extensions.StringExtensions.TrimFirstLine(StringBuilder builder)
       at ExCSS.StyleSheet.ToString(Boolean friendlyFormat, Int32 indentation)
       at ExCSS.StyleSheet.ToString()

```

```
public static StringBuilder TrimFirstLine(this StringBuilder builder)
        {
            if (builder.Length > 0) // this check must be moved to "while"
            {
                while (builder[0] == '\r' || builder[0] == '\n' || builder[0] == '\t')
                {
                    builder.Remove(0, 1);
                }
            }

            return builder;
        }
```

**Comment by TylerBrinks** [comment]
Can you provide any detail on what was being parsed?  There's not enough detail here to understand what happened.

**Comment by MaceWindu** [comment]
Well, I was testing different inputs and it was failing like that on latest released version on empty string (string.Empty).
On current code base it doesn't fail due to some other changes since last release, so I have no inputs to reproduce it now using parser. But you still can reproduce it using isolated test for this extension method (and TrimLastLine):
```
new StringBuilder("\r\n").TrimLastLine();
new StringBuilder("\r\n").TrimFirstLine();
```

**Comment by MaceWindu** [comment]
Looks like #64 tried to fix the same issue, but introduced this error.

**Comment by 1nTheZ0ne** [comment]
I can confirm that this exception is being thrown when the input string is empty, resulting in every collection in ExCSS.StyleSheet having a count of zero.

**Comment by TylerBrinks** [comment]
Looking into it.
