### ISSUE TITLE
Fails parsing bootstrap.css

### ISSUE THREAD

**Issue by fewzionph** [TylerBrinks/ExCSS#75]
I wanted to use ExCSS to parse bootstrap and add/edit class selectors in order to isolate CSS that will be inserted into a JS client-side widget.

Unfortunately the attached bootstrap.css file failed after/at:

audio:not([controls]) {
  display: none;
  height: 0;
}
[hidden],
template {
  display: none;
}

No further Rulesets were parsed.

Example code:

        static void Main()
        {
            var parser = new ExCSS.ExCSS();
            string css = File.ReadAllText(@"..\bootstrap.css.txt");
            Stylesheet ss = parser.Parse(css);
            foreach (RuleSet rs in ss.RuleSets) {
                foreach (Selector rss in rs.Selectors){
                    Console.WriteLine(rss.ToString());
                }
            }
            Console.ReadKey();
}

[bootstrap.css.txt](https://github.com/TylerBrinks/ExCSS/files/32634/bootstrap.css.txt)

**Comment by TylerBrinks** [comment]
Can you provide any detail?  Usually we can narrow it to what type of rule is failing and what type is being parsed versus what's expected.

**Comment by oguimbal** [comment]
I've had several issues like this one too, the issue being that ExCss parser fails silently (and stops parsing) sometimes when encountering invalid css. 
I've realised it when trying to parse bootstrap as well.
Bootstrap contains a lot of invalid css [(css hacks, mostly).](https://css-tricks.com/snippets/css/browser-specific-hacks/)

I've implemented https://github.com/oguimbal/ncss as an alternative when you need to parse dirty things.

**Comment by TylerBrinks** [comment]
what would be helpful is if you could submit a failing unit test.  Otherwise isolating the issue can be a bit difficult.
