### ISSUE TITLE
HtmlColor does not support hsl or hsla

### ISSUE THREAD

**Issue by on3al** [TylerBrinks/ExCSS#79]
Hsla colors are not recognized as an html color. They are recognized as a generic function.

The following should be valid HtmlColor:

 /* HSL model, added to CSS3 */
 p { color: hsl(0, 100%, 50%) } /* red */
 p { color: hsl(120, 100%, 50%) } /* green */
 p { color: hsl(120, 100%, 25%) } /* dark green */
 p { color: hsl(120, 100%, 75%) } /* light green */
 p { color: hsl(120, 50%, 50%) } /* pastel green */

 /* HSL model with alpha channel */
 p { color: hsla(120, 100%, 50%, 1) } /* green */
 p { color: hsla(120, 100%, 50%, 0.5) } /* semi-transparent green */
 p { color: hsla(120, 100%, 50%, 0.1) } /* very transparent green */

**Comment by TylerBrinks** [comment]
I have a fully rewritten version written for the current versions of .NET.  This should be addressed in the upcoming release.
