### ISSUE TITLE
.NET Core/.NET Standard support

### ISSUE THREAD

**Issue by madskristensen** [TylerBrinks/ExCSS#85]
It would be nice if this could be used from .NET Core.

**Comment by TylerBrinks** [comment]
Version 3 which is to be released soon is fully rewritten and runs on .Net core.  I'm working to get it checked in for an initial review in the very near future

Sent from my iPhone

On Jul 30, 2017, at 11:21 AM, Mads Kristensen <notifications@github.com<mailto:notifications@github.com>> wrote:


It would be nice if this could be used from .NET Core.

**Comment by TylerBrinks** [comment]
Would you mind helping me connect with someone who knows the best way to configure a project to target as many platforms as possible?  I just uploaded the first release of version 3 and I'm sure the project could use help being structured properly.

**Comment by shobman** [comment]
@TylerBrinks I'm happy to look over the code.  I'm looking forward to the net standard 2.0 support so more than happy to help out.

**Comment by madskristensen** [comment]
Do you have a MyGet feed or somewhere we can consume v3.0? Or do we have to build from source at the moment?

**Comment by shobman** [comment]
@TylerBrinks, to create the nuget with the dotnet 2.0 sdk run the following from the project folder.
`dotnet pack -c ="Release"`

The nuget meta properties are pulled directly from the .csproj file. You'll notice I added
`<PackageVersion>3.0.0-beta1-20170822</PackageVersion>`.

Read here for the full list of meta properties:
https://github.com/dotnet/docs/blob/master/docs/core/tools/csproj.md#nuget-metadata-properties

And for dotnet pack options read here:
https://github.com/dotnet/docs/blob/master/docs/core/tools/dotnet-pack.md

Do you want me to add this as a build.cmd or something like that?

**Comment by TylerBrinks** [comment]
I'll take a shot at it and see how it turns out.  It'd be nice to get some of the meta data filled in.

**Comment by TylerBrinks** [comment]
I could use a hand getting the target framework set up correctly.  I published a myget feed to https://www.myget.org/F/excss/api/v3/index.json, but adding the package to a project yields the error below.  I'm sure that's simple to configure correctly, but I'm out of bandwidth for the week.

Package ExCSS 1.0.0 is not compatible with netcoreapp1.1 (.NETCoreApp,Version=v1.1). Package ExCSS 1.0.0 supports: net40 (.NETFramework,Version=v4.0)
Package restore failed. Rolling back package changes for 'ConsoleApp1'.

**Comment by shobman** [comment]
If you set the target framework to <TargetFramework>netstandard1.1</TargetFramework> then minimum support will be net core 1.1 or net full 4.5. See https://docs.microsoft.com/en-us/dotnet/standard/net-standard#net-implementation-support

It looks like you're trying to pull your package into a net 4.0 app.  Which you can probably do if you update your target framework to <TargetFramework>netstandard1.1;net40</TargetFramework>

Haven't tried it. But it's worth a shot. Or else I suggest dropping support for 4.5 if you can.

Let me know how you get on.

**Comment by cipchk** [comment]
hi gays, is there any news about?

**Comment by pil78** [comment]
Hi guys,
There is an error in .csproj file (wrong syntax): 
currently it has <TargetFramework>netstandard1.1;net462</TargetFramework>
but should be <TargetFrameworks>netstandard1.1;net461</TargetFrameworks>
Yaroslav

**Comment by emiliano84** [comment]
thanks to HockeyJustin there is a new fork and nuget package with the latest changes, if interested :)
https://github.com/HockeyJustin/ExCSS_Core

**Comment by madskristensen** [comment]
Closing since https://github.com/HockeyJustin/ExCSS_Core is now an option. Thanks
