### ISSUE TITLE
Get all url in css file

### ISSUE THREAD

**Issue by phucphanJaneto** [TylerBrinks/ExCSS#91]
Hi,
I am using .Net Framework 4.6.2 and uses this library version 2.0.6. 

Can I get all urls (includes image url, font face url) from css string by ExCSS?

**Comment by YMoustarham** [comment]
I was Able To Do this with a loop on faceDirective.Declarations instead of directly accessing the value from
faceDirective.Src
example
` List<string> fontUrls = new List<string>();
                   foreach (Property declaration in faceDirective.Declarations.Where(x=>x.Name=="src"))
                   {
                       fontUrls.Add(declaration.Term.ToString());
                   }`

**Comment by phucphanJaneto** [comment]
It works for me. 
Many thanks @YMoustarham
