### ISSUE TITLE
Can't load project in VS2015?

### ISSUE THREAD

**Issue by jhndnnqsc** [TylerBrinks/ExCSS#92]
When I clone master and load the solution both ExCSS and ExCSS.Tests projects fail with the following error

`The default XML namespace of the project must be the MSBuild XML namespace. If the project is authored in the MSBuild 2003 format, please add xmlns="http://schemas.microsoft.com/developer/msbuild/2003" to the <Project> element. If the project has been authored in the old 1.0 or 1.2 format, please convert it to MSBuild 2003 format.  \ExCSS\src\ExCSS\ExCSS.csproj
`

Googling around it looks as though that error is related to loading a VS2017 project into VS2015. Is VS2015 supported?

**Comment by TylerBrinks** [comment]
There is no plan to support legacy versions of Visual Studio.
