### ISSUE TITLE
Any documentation on 2.0 version?

### ISSUE THREAD

**Issue by jhndnnqsc** [TylerBrinks/ExCSS#93]
Is there any documentation on the 2.0 version available via Nuget? I'm trying to determine the following

- basic use case of looking up a style via class name
- how/if the tree is represented so if something isn't defined in a class selector it falls back to the type selector, etc
- is it possible to add custom tree definitions for custom type selections?
- are custom pseudo-classes with arguments supported ( like :lang())?
- is this project still alive?

**Comment by TylerBrinks** [comment]
You can look back through the project's readme.md history, but generally speaking version 2 is obsolete and all development is focused on version 3 which will be added to the NuGet public repository in the near future.
