### ISSUE TITLE
Basic Example not a true example

### ISSUE THREAD

**Issue by kiebor** [TylerBrinks/ExCSS#94]
> var parser = new StylesheetParser();
> var stylesheet = parser.Parse(".someClass{color: red; background-image: url('/images/logo.png')");
> 
> var rule = stylesheet.Rules.First()
> var selector = rule.SelectorText; // Yields .someClass
>     var color = rule.Style.Color;
> var image = rule.Style.BackgroundImage; // url('/images/logo.png')

The above snippet as described in the 'Basic example' does not work in practice and contains no actual working code example.

Once a string is parsed to StyleSheet, there is no Rules member to expose; instead there are multiple rule members:
-         StyleSheet.CharacterSetRules
-         StyleSheet.MediaRules
-         StyleSheet.FontfaceSetRules
-         StyleSheet.ImportRules
-         StyleSheet.PageRules
-         StyleSheet.NamespaceRules

None of these Collections contain any 'rule' object that exposes 'Style'; instead they are IEnumerable of IRule which is consumable as:
-         Type [Enum]
-         StylesheetText <= can expose 'Text' (the actual css text)

In an attempt to guess how to use this library, I tried to iterate over 'Children' from 'StyleSheet' and discovered I had the same resulting option (StylesheetText) to work with...

My question is, where is the documentation, are there any true examples or guidance available?

**Comment by trevorsg** [comment]
You can iterate/recurse over the Children property, which is on every StylesheetNode, until you have your hands on a node you care about. However, it seems some classes are internal and they do not implement the public interface (e.g. StyleRule does not implement IStyleRule), so I think you may need to resort to reflection in some cases.

**Comment by kiebor** [comment]
Thanks @trevorsg. That does help.

What I'm trying to do is digest a style sheet so it is readable as a set of tabulated classes. i.e. each class is a table of css properties and values.

By recursing over the children of the parsed 'StyleSheet', I have my list of classes, but can't access their properties or assigned values; they are only usable as 'StylesheetText'. Whereas, I was expecting to be able to access 'SelectorText' and other named properties (i.e. Style etc.).

I've tried reflection to try and understand what IStylesheetNode actually means and whether I can cast to something more usable:

```c#
            styleSheet.Children.ToList().ForEach((parent) =>
            {
                Debug.WriteLine(parent.StylesheetText.Text);
                try
                {
                    Debug.WriteLine($"Has {parent.Children.ToList().Count.ToString()} Children");
                    parent.Children.ToList().ForEach((child) =>
                    {
                        Debug.WriteLine(child.StylesheetText.Text);
                        Type _childtype = child.GetType();
                        Debug.WriteLine($"Has {child.Children.ToList().Count.ToString()} Children");
                        Debug.WriteLine($"{_childtype.Name} is [{(_childtype.IsPublic ? "PUBLIC" : "PRIVATE")}{(_childtype.IsNested ? ", INTERNAL" : "")}] and{(_childtype.IsSealed ? "" : " not")} [SEALED]");

                    });

                }
                catch (NullReferenceException nullex)
                {
                    Debug.WriteLine("Object does not have any children");
                }
                catch (Exception ex)
                {
                    Debug.WriteLine(ex.Message);
                }
            });
```
All Selector classes are internal :(

Frustratingly, the basic example gave me exactly what I want and an immediate method for achieveing it. Shame it isn't actually a working code sample.

Any idea how I can achieve the same?

**Comment by TylerBrinks** [comment]
I don't understand your use case.  It might be easier to help if you provide a known input and expected output.  The API was intentionally designed so as not to require reflection.

**Comment by trevorsg** [comment]
I figured out my issue without using reflection. It was a matter of figuring out the right types to reference (I was trying to use IStyleRule instead of IRule when I discovered that nothing actually implements IStyleRule).

**Comment by kiebor** [comment]
> I don't understand your use case

Simply I want to read a css file into an object I can interrogate in the way described in your basic example.

Ultimately, I want to consume the file content into a list of classes which I can tabulate. The tables would consist of css property and value pairs.

e.g.
from => .someClass{color: red; background-image: url('/images/logo.png')
to 
[Table with name = SomeClass]

| PropertyName | PropertyValue |
| --- | --- |
| color | red |
| background-image | url('/images/logo.png') |

In order to achieve this, I was hoping to be able to interrogate the Style Property as illustrated in the basic example, and reconstruct as my own set of objects (i.e. tables).

I have resorted to string splitting on the parent StylesheetText at ';' and then again on the substring at ':'.

**Comment by nazuke** [comment]
Piggybacking on this @TylerBrinks, I'm finding the same problem, and would like to do something similar to what @kiebor is trying to achieve, i.e. iterate the styles and extract certain property values.

If I try and pack the example from the README into a short test, like this:

    public void TestExCssExample ()
    {
      var parser = new StylesheetParser();
      var stylesheet = parser.Parse( ".someClass{color: red; background-image: url('/images/logo.png')" );
      var rule = stylesheet.Rules.First();
      var selector = rule.SelectorText; // Yields .someClass
      var color = rule.Style.Color;
      var image = rule.Style.BackgroundImage; // url('/images/logo.png')
    }

...then I get this error:

> Error	CS1061	'Stylesheet' does not contain a definition for 'Rules' and no extension method 'Rules' accepting a first argument of type 'Stylesheet' could be found (are you missing a using directive or an assembly reference?)

...for:

> stylesheet.Rules.First();

Also, there's a semi-colon missing on this line in the example:

    var rule = stylesheet.Rules.First()

Many thanks!

**Comment by dbracun** [comment]
@TylerBrinks The problem is that StyleRule class is internal and it does not implement IStyleRule, so neither Selector nor SelectorText properties are publicly exposed. That basically makes it impossible to traverse the object tree and find the rule you're looking for. Please fix this in version 3 because it is currently unusable without reflection or parsing whole style texts as someone already mentioned.

**Comment by emiliano84** [comment]
thanks to HockeyJustin there is a new fork and nuget package with the latest changes, if interested :)
https://github.com/HockeyJustin/ExCSS_Core

**Comment by TylerBrinks** [comment]
Project resurrected. Please verify in version 4.0 if the issue still exists.
