### ISSUE TITLE
IStyleFormattable.ToCss() always seems to use UTF-8 encoding. Can this be configured?

### ISSUE THREAD

**Issue by T-Hugs** [TylerBrinks/ExCSS#95]
In the source I have a number of escaped character sequences, e.g.

    .some-selector::before {
        content: "\EA60";
    }

When I parse and re-serialize with ExCSS it converts the escaped character to the actual unicode character, like this: 

    .some-selector::before { content: "" }

Right now I have two workarounds:

1. Always add @charset "utf-8"; to my CSS files (or at least use ExCSS to ensure it is there)
2. Post-process the output of ExCSS to convert these back into ascii-compatible escape sequences.

Thanks for your help.

**Comment by trevorsg** [comment]
Looks like 1. is not really supported. From RuleList.cs...

    if (rule.Type == RuleType.Charset)
    {
        throw new ParseException("Cannot insert Charset rule");
    }
