### ISSUE TITLE
Test Project Doesnt Build

### ISSUE THREAD

**Issue by decherneyge** [TylerBrinks/ExCSS#96]
I cloned the repo to try to investigate  #94  but I cant get ExCSS.Tests to compile. It looks like the references are not configured properly.

**Comment by Drakkins** [comment]
Look at pull request, it will fix it

**Comment by emiliano84** [comment]
thanks to HockeyJustin there is a new fork and nuget package with the latest changes, if interested :)
https://github.com/HockeyJustin/ExCSS_Core

**Comment by TylerBrinks** [comment]
Please verify in version 4.0 if the issue still exists.
