### ISSUE TITLE
Take a look at pull requests

### ISSUE THREAD

**Issue by Drakkins** [TylerBrinks/ExCSS#99]
There are waiting pull requests since December 2017, please take a look at it or share project ownership.
This project has too many issue and these pull requests are vital.

**Comment by emiliano84** [comment]
thanks to HockeyJustin there is a new fork and nuget package with the latest changes
https://github.com/HockeyJustin/ExCSS_Core

**Comment by TylerBrinks** [comment]
Project resurrected :)
